### ISSUE TITLE
getting vulnerabilities errors

### ISSUE THREAD

**Issue by ldb2000** [Wh1teRabbitHU/ImageToEpaperConverter#7]
hi,

When I try to install ImageToEpaperConverter, I have the following error:
```
➜  ImageToEpaperConverter git:(master) ✗ npm install
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'node-png@0.4.3',
npm WARN EBADENGINE   required: { node: '0.8.x' },
npm WARN EBADENGINE   current: { node: 'v17.4.0', npm: '8.3.1' }
npm WARN EBADENGINE }

up to date, audited 98 packages in 550ms

13 packages are looking for funding
  run `npm fund` for details

3 vulnerabilities (1 moderate, 2 high)

To address issues that do not require attention, run:
  npm audit fix

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.
```

Any help?

**Comment by Wh1teRabbitHU** [comment]
I can take a look, but if you use locally, it shouldn't cause any issue

**Comment by Wh1teRabbitHU** [comment]
Sadly it's not fixable from this library, because the vulnerabilities are comming from the following library:
https://github.com/guyonroche/imagejs

I close this issue for now, but if you can ask the owner of that other library to make a security update, I'll update the dependency version!
